name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc, clang]
    env:
      CC: ${{ matrix.compiler }}
      LSAN_OPTIONS: verbosity=1:log_threads=1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compilation
      run: ./toolchain/bin/make app
