name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain dependencies
      run: cd toolchain && git submodule update --init --recursive
    - name: Build Toolchain
      run: make && make install
    - name: Compilation
      run: ./toolchain/bin/make app
